### ISSUE TITLE
MCW-Securing-the-IoT-end-to-end

### ISSUE THREAD

**Issue by Gvashi** [microsoft/MCW-Securing-the-IoT-end-to-end#1]
There is an error in Exercise 2:->Task 5:-> Setp3
This step is unable to generating Registration Id and the Endorsement Key.

**Comment by givenscj** [comment]
Hi there,

Are you running the labs with the provided IOT device that was created in the ARM template or on some other device?

**Comment by givenscj** [comment]
I found the issue.  The extraction process overwrites the permissions in the user directory.  I have updated labs.  Waiting for the pull request to complete.  In the mean time you would execute 'sudo chown -R $USER ~/.'  to take over the directory and execute the commands after the tar commands.

**Comment by Gvashi** [comment]
Hi ,
Are you running the labs with the provided IOT device that was created in the ARM template.

**Comment by Gvashi** [comment]
Gaurav Vashishta would like to recall the message, "[microsoft/MCW-Securing-the-IoT-end-to-end] MCW-Securing-the-IoT-end-to-end (#1)".

**Comment by Gvashi** [comment]
Hi ,
I am just using the IOT device that was created in the ARM template.

**Comment by DawnmarieDesJardins** [comment]
Correcting Pull Request merged and HTML files updated.  Closing this issue as resolved.
