### ISSUE TITLE
June 2020 Update Suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Securing-the-IoT-end-to-end#10]

**Comment by timahenning** [comment]
Update

- Pull in latest agent code (versions are pre-set so that they ensure success)

Add

- Implement a manual failover for High-Availability of Iot Hub (https://docs.microsoft.com/en-us/azure/iot-hub/tutorial-manual-failover)
- Device missing detection
- 3rd attack vector for detection?
- Add baseline checks (https://docs.microsoft.com/en-us/azure/asc-for-iot/concept-baseline)
- Add in extra investigation steps (https://docs.microsoft.com/en-us/azure/asc-for-iot/how-to-investigate-device)
-

**Comment by paswani** [comment]
Add in extra investigation steps - Azure monitor too

**Comment by femi-san** [comment]
``
![image](https://user-images.githubusercontent.com/33995485/84092529-88770200-a9ef-11ea-8d7d-e94315f8086e.png)

**Comment by paswani** [comment]
> Update
> 
> * Pull in latest agent code (versions are pre-set so that they ensure success)
> 
> Add
> 
> * Implement a manual failover for High-Availability of Iot Hub (https://docs.microsoft.com/en-us/azure/iot-hub/tutorial-manual-failover)
> * Device missing detection
> * 3rd attack vector for detection?
> * Add baseline checks (https://docs.microsoft.com/en-us/azure/asc-for-iot/concept-baseline)
> * Add in extra investigation steps (https://docs.microsoft.com/en-us/azure/asc-for-iot/how-to-investigate-device)

Tim can we include your IoT comos DB workshop as a reference link here?  https://github.com/AzureCosmosDB/scenario-based-labs/blob/master/IoT/HOL%20step-by%20step%20-%20Cosmos%20DB%20scenario-based%20labs%20-%20IoT.md

**Comment by idbanham** [comment]
Sorry this is kind of last minute, been off work for a few months thanks to Covid....

Hands-on lab\Resources\template.json has hard-coded references to east-us. Messes up your deployment slightly...

Exercise 3, Task 2 - The text for the DeviceID is OilWells001, the images show oilwells001. If you put the upper case version in, it will stop the Security Agent from starting as the script for creating that uses oilwells001

Exercise 5 - It's worth mentioning the options for the trigger_events script as you need to use the --remidiate option to kill the process and you can also run it with multiple open ports. Can make the Alerts a bit more interesting.

Exercise 7 - Needs updating to TSI PAYG as that GA's very soon.

General - you spend a load of time setting up a software TPM and DPS when you could just get IoT Edge Running with the connection string. Put IoT Edge with a TPM as a separate Lab. It's a useful exercise in itself, but a distraction here. You could use that time to set up another VM with an SDK device with the Security Agent and run the different attack scripts from there. Time wise at least 80% of the "typing time" is setting stuff up, the amount of time you actually spend in the tool you're supposed to be learning about is fairly minimal. Could more of the setup be automated?

Nano editor in an SSH session in a powershell window has no keyboard triggered paste capability, you can paste with a right mouse-click but it's a bit unreliable. Attempting Ctrl-V takes you to the end of the file.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #14
