### ISSUE TITLE
syntax error near unexpected token `OPENSSL,'

### ISSUE THREAD

**Issue by pietrobr** [microsoft/MCW-Securing-the-IoT-end-to-end#12]
Hi running in the Edge VM provided with the sample ( Ubuntu 16.04)

./configure --prefix=${HOME}/local --disable-hwtpm 

I get the following error

./configure: line 12268: syntax error near unexpected token `OPENSSL,'
./configure: line 12268: `PKG_CHECK_MODULES(OPENSSL,  openssl >= 1.0.1 )

To solve you need to install this ( Ubuntu 16.04)

apt-get install pkg-config

**Comment by DawnmarieDesJardins** [comment]
@givenscj 
Hi Chris!  Please review and advise.

**Comment by givenscj** [comment]
Ah, yes, the 16.04 path is a bit different.  Labs were originally targeted at 18.04.  I will look at running at 16.04 again to make sure this is captured.  Thanks.

**Comment by givenscj** [comment]
Ok, I was able to replicate this, if you copy the commands in batches, they will skip (and thusly cause this error).  there is a not in the labs to run each line separately to ensure success.
