### ISSUE TITLE
Could not start IoT Edge with TPM

### ISSUE THREAD

**Issue by pietrobr** [microsoft/MCW-Securing-the-IoT-end-to-end#13]
I have modified the yaml config file to use TPM, I reset IoT Edge, but it fails to start.
In the journal I see: HSM API returned an invalid null response

Jun 09 17:06:01 oilwells-edgevm-pietrobr iotedged[5963]: 2020-06-09T17:06:01Z [INFO] - Starting provisioning edge device via TPM...
Jun 09 17:06:01 oilwells-edgevm-pietrobr iotedged[5963]: 2020-06-09T17:06:01Z [ERR!] - The daemon could not start up successfully: Could not initialize DPS provisioning client
Jun 09 17:06:01 oilwells-edgevm-pietrobr iotedged[5963]: 2020-06-09T17:06:01Z [ERR!] -         caused by: HSM API returned an invalid null response
Jun 09 17:06:01 oilwells-edgevm-pietrobr iotedged[5963]: Error: Time:Tue Jun  9 17:06:01 2020 File:/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/deps/utpm/src/tpm_comm_linux.c Func:tpm_usermode_resmgr
Jun 09 17:06:01 oilwells-edgevm-pietrobr iotedged[5963]: Error: Time:Tue Jun  9 17:06:01 2020 File:/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/deps/utpm/src/tpm_comm_linux.c Func:tpm_comm_create Lin
Jun 09 17:06:01 oilwells-edgevm-pietrobr iotedged[5963]: Error: Time:Tue Jun  9 17:06:01 2020 File:/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/deps/utpm/src/tpm_codec.c Func:Initialize_TPM_Codec Lin
Jun 09 17:06:01 oilwells-edgevm-pietrobr iotedged[5963]: 2020-06-09T17:06:01Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/hsm_client_tpm_device.c:initialize_tpm_device:273) Failure initi
Jun 09 17:06:01 oilwells-edgevm-pietrobr iotedged[5963]: 2020-06-09T17:06:01Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/hsm_client_tpm_device.c:hsm_c

**Comment by DawnmarieDesJardins** [comment]
@givenscj 
Hi Chris!  Please review and advise.

**Comment by givenscj** [comment]
This part of the lab is fairly easy to make errors in.  I would double check the values entered into the config file are correct and that you only selected one config path.  If they are valid, I would then go back and make sure the software TPM did download and is running.

**Comment by pietrobr** [comment]
Hi thank you for the suggestion.
I have rerun from the beginning, the TPM is started and listening on port 2321 and 2322
![image](https://user-images.githubusercontent.com/2890569/85261667-c999f800-b46c-11ea-95c4-be9fdf0ede10.png)
and  the TPM resource manager
![image](https://user-images.githubusercontent.com/2890569/85261788-01a13b00-b46d-11ea-8eee-8154a4934f23.png)
getting the registration Id and Endorsement Key
![image](https://user-images.githubusercontent.com/2890569/85261859-22699080-b46d-11ea-8e93-3c92772d427d.png)

I have configure the config.yaml
![image](https://user-images.githubusercontent.com/2890569/85262068-82f8cd80-b46d-11ea-867c-16fc330a80a6.png)

What I haven't done because  I used a software TPM is running the instructions after 
tpm=$(sudo find /sys -name dev -print | fgrep tpm | sed 's/.\{4\}$//')
tpm is an empty string

I put an error export of the this

 sudo journalctl -u iotedge

at [this link ](https://oilwellsstoragepietrobr2.blob.core.windows.net/dwnl/error.txt)

**Comment by givenscj** [comment]
Hi there, I see you used the TPM path.  It could be something is not quite working with that route.  Can you switch to the manual path instead with device connection string?

**Comment by pietrobr** [comment]
Yes it works with the manual connection string. But the main purpose of the lab is using TPM. If I use hyperv TPM emulated  instead downloading the software one I was able to make it run as I have described here  https://azureiot.dev/2020/06/18/iot-edge-with-tpm-and-azure-security-central-for-iot/

**Comment by pietrobr** [comment]
Hi @givenscj any update here?

**Comment by DawnmarieDesJardins** [comment]
@timahenning @givenscj 
Please review & advise

**Comment by shmiglan-arch** [comment]
Agree on this, when I tried working with TPM Device Provisioning,  I get an error as below, Manual Provisioning works. The log when we get an error with TPM is below -- Logs begin at Mon 2020-07-13 14:41:19 UTC, end at Mon 2020-07-13 16:56:01 UTC. --
Jul 13 16:41:49 oilwells-edgevm-shmiglan systemd[1]: Stopped Azure IoT Edge daemon.
Jul 13 16:41:49 oilwells-edgevm-shmiglan systemd[1]: Started Azure IoT Edge daemon.
Jul 13 16:41:49 oilwells-edgevm-shmiglan iotedged[19026]: 2020-07-13T16:41:49Z [INFO] - Using config file: /etc/iotedge/config.yaml
Jul 13 16:41:49 oilwells-edgevm-shmiglan systemd[1]: iotedge.service: Main process exited, code=exited, status=1/FAILURE
Jul 13 16:41:49 oilwells-edgevm-shmiglan systemd[1]: iotedge.service: Unit entered failed state.
Jul 13 16:41:49 oilwells-edgevm-shmiglan systemd[1]: iotedge.service: Failed with result 'exit-code'.

**Comment by givenscj** [comment]
I went through this a few days ago and unfortunately the software TPM will not work with the current lab design/software.  We will have to table until the next update, the path to completion is to continue to to the manual connection.

**Comment by DawnmarieDesJardins** [comment]
Thanks for the information @givenscj 
Marking this issue as an enhancement for the next scheduled update.

**Comment by givenscj** [comment]
vTPM has now been implemented and verified using new Gen2 Windows 10 \ HyperV "server" image.
