### ISSUE TITLE
Recommendations 

### ISSUE THREAD

**Issue by shmiglan-arch** [microsoft/MCW-Securing-the-IoT-end-to-end#15]
Please replace IoT Provisioning Service with IoT Device Provisioning Service in the full document
Slide 14 as well as Hands-on MCW talks about routing data form IoT Hub to Service Bus, there is no service bus in the SA (Analytics).
Major - Though the Case Study talks about Security Center and Analytics use case, in implementation, what is shown is only the Security Center. The Analytics use case is not shown. SA (Analytics) is not demonstrated at all.
HOL step-by-step - Securing the IoT end-to-end.md- Task 3, Enable Azure Audit logging, One screenshot missing how to enable logs and link it to oilwells-logging-[YOUR INIT].

**Comment by DawnmarieDesJardins** [comment]
@givenscj @timahenning 
Please include as feedback with PR #14

**Comment by shmiglan-arch** [comment]
Securing the IoT end-to-end hands-on lab step-by-step
Task 5: 
Run the following commands to start a TPM resource manager:
cd
sudo apt-get install -y autoconf
 
**Recommendation -: 
Run the following commands to start a TPM resource manager in a different power shell window :_**

_Task 2: Configure the IoT Edge agent_
 
![image](https://user-images.githubusercontent.com/67866123/87334568-7b07e700-c55c-11ea-8463-e286e997ddb3.png)

 
 
The above screenshot is attached in the MCW. The highlighted provisioning:  should be commented as the DPS TPM provisioning is selected.

**Comment by givenscj** [comment]
The screen shot was in the correct place.  I added another for the manual path.  We also added comments to tell people to press enter based on another request for the TPM step.
