### ISSUE TITLE
Could not find linux server option under advance settings of log analytics workspace

### ISSUE THREAD

**Issue by anushabc** [microsoft/MCW-Securing-the-IoT-end-to-end#16]
In Exercise 5 , Task 2 , Step 6  was not able to find linux server option under advance settings. 

![Screenshot (29)](https://user-images.githubusercontent.com/66515706/91659553-067a0f00-eaee-11ea-959b-b0d05076db90.png)

It can be found by clicking on agents management under advance settings , connected sources tab.

![Screenshot (30)](https://user-images.githubusercontent.com/66515706/91660012-0fb8ab00-eaf1-11ea-9507-b55ca7459025.png)

**Comment by givenscj** [comment]
The UI has changed, you can follow the link on that page to take you to the new location.  Or just navigation to "Agent Management".

Updated in latest commit.
