### ISSUE TITLE
iotedge status is getting failed

### ISSUE THREAD

**Issue by Gvashi** [microsoft/MCW-Securing-the-IoT-end-to-end#3]
Exercise 3 :-> task 2:-> Subtask 11 
please take a look on screenshot
![001](https://user-images.githubusercontent.com/53901647/64342662-9f279d00-d008-11e9-93f1-84d5f7ef880f.JPG)

![002](https://user-images.githubusercontent.com/53901647/64342771-da29d080-d008-11e9-85f3-31671b2451df.JPG)

**Comment by DawnmarieDesJardins** [comment]
@timahenning
Hi Tim - please review & advise.  Thanks!

**Comment by timahenning** [comment]
We will look into it and let you know.

Tim

**Comment by Gvashi** [comment]
Thanks a lot

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Gvashi** [comment]
Please take a look @DawnmarieDesJardins

**Comment by DawnmarieDesJardins** [comment]
@Gvashi 
Hello.  Our authors are looking into the issue and will get back to you by end of week.

**Comment by givenscj** [comment]
I just went through the labs.  They are still working as intended to this point.  It could be possible that you did not fill out the yaml file correctly.  What path (of the three) did you take to setup the yaml file?

**Comment by Gvashi** [comment]
I am using the same path which is mention in the lab guide,
and i checked the code for ymal file in online compiler
