### ISSUE TITLE
Unable to find the Directory

### ISSUE THREAD

**Issue by Gvashi** [microsoft/MCW-Securing-the-IoT-end-to-end#4]
Hi 
Please help me to find the Directory, when I run the command "cd Azure-IoT-Security-Agent-C/release" it shows that no such directory found

Exercise 4 Task 1 can you please verify these commands

**Comment by timahenning** [comment]
Gvashi,

Thank you for submitting your issue.  We will look into it soon.  You can find our support goals: https://microsoftcloudworkshop.com/

Tim

**Comment by givenscj** [comment]
Hi Gvashi,

Seems they moved the release binaries on us : https://github.com/Azure/Azure-IoT-Security-Agent-C/commit/610fc4fcd9c93e51982bebcc0ac076387447f2cc

I have update the repo with the new steps.

**Comment by DawnmarieDesJardins** [comment]
@givenscj @Gvashi @timahenning 
Thanks Chris.  
Gaurav, I've rerun the HTML script to update those documents.  If you're using the HTML format, please allow a few minutes for them to refresh.  Closing the issue as resolved.
