### ISSUE TITLE
Images not showing in HTML files

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Securing-the-IoT-end-to-end#6]
Please review .md coding.  Images show inside the repo for all documents, but not in the HTML version:

Repo view:
![image](https://user-images.githubusercontent.com/39317565/70746042-f741ff80-1cd9-11ea-92b0-58f7810d87b7.png)

HTML file view (alt-text only shows):
![image](https://user-images.githubusercontent.com/39317565/70746232-6b7ca300-1cda-11ea-9f85-912026748dda.png)

**Comment by timahenning** [comment]
Is it all images? Is it just one image?

**Comment by DawnmarieDesJardins** [comment]
@timahenning
All images on all four documents.

**Comment by DawnmarieDesJardins** [comment]
@timahenning
Thanks Tim. The PR corrected most of the images.  Before the HOL is fixed.  Only missing the Solution architecture (high level & analytics images) from the step-by-step lab.  

The infographic image on both the student & trainer guides, and the preferred solution image in the trainer guide are still not in the HTML but also broken link in the repo now as well.

**Comment by timahenning** [comment]
ok - I will fix those today.

**Comment by DawnmarieDesJardins** [comment]
Closing issue, fixed with merged PRs #7 & #8
